#!/bin/bash

#When script executed
#1. Gets all what is in WATCH_DIR
#2. Resolves all links to REALPATH
#3. Moves all FILEs from WATCH_DIR to BACKUP_ROOT/REALPATH

#Set dotglob to match dot-files with pure *. Without it there going to be . and .. directories included
shopt -s dotglob

readonly WATCH_DIR='/home/pyro/Documents/backup-folder-gather'
readonly BACKUP_ROOT='/mnt/vault/storage/important/backups'

for FILE in "$WATCH_DIR"/*
do
  echo "$FILE"
  REALPATH="$(realpath "$FILE")"
  echo "$REALPATH"
  DIR="$(dirname "$REALPATH")"
  echo "mv "$FILE" "$BACKUP_ROOT""$REALPATH""
  mkdir -p "$BACKUP_ROOT""$DIR"
  mv "$FILE" "$BACKUP_ROOT""$REALPATH"
done
